### ISSUE TITLE
Syncs

### ISSUE THREAD

**Issue by Zod-** [wildstarnasa/NASADocs#11]
How did you guys get this data? I'd like to update this repository.

**Comment by Togglebutton** [comment]
The method I was using for pulling all of the addons efficiently doesn't seem to work anymore.  I am not longer playing actively, maybe someone else with access can get newer data.

**Comment by Zod-** [comment]
I sent a message to the people running http://feed.wildweave.net/en/datamining, they can probably help.

**Comment by Zod-** [comment]
I managed to make an extraction tool with [this](https://github.com/jasoncouture/StrangeSoft.WildStar). I'm not sure about everything else in this repository like the events, packages, _G dumps, etc. so I was wondering if I should just put it in a new repository.

**Comment by Togglebutton** [comment]
Many of those things haven't been updated in ages. Events was pulled from the files that are sourced to Houston. _G dumps are of minimal use now that there is included API documentation in Houston. The Carbine addons are the most useful thing, as they are living examples of using the API. You can still push them here if you like. However, if you intend to really keep up with it, a new repository would probably be better.

**Comment by Zod-** [comment]
Yeah I intend to keep it up to date to also see the changes they are making to them. I will put it in a new repository then.
Thanks!
