### ISSUE TITLE
Can we get a sync of the Carbine Addons?

### ISSUE THREAD

**Issue by baslack** [wildstarnasa/NASADocs#9]
Been like three months, anyone still about here? If so, can I get a sync on the Carbine Addons. Coming back to the game after a month off and I've a couple of reports of issues with Killroy, which would be easier to track if I can see the changes in ChatLog.lua

**Comment by Sinaloit** [comment]
I haven't been playing for a while but I do respond to requests when I have time.  If you like I could add you to the Repo so you can upload the changes.

**Comment by baslack** [comment]
I'm happy to help out however I can. Have to look up that opener application for the game archive, but once I have it I can do these syncs and not have to bother you. Thanks for getting back to me so promptly, Sinaloit.
